name: Remove Background Action

on:
  push:
    branches: [ "main" ] # يشتغل الأكشن عند كل رفع للكود على الفرع الرئيسي
  workflow_dispatch: # يتيح لك تشغيل الأكشن يدوياً من واجهة جيتهاب

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # جلب ملفاتك من المستودع للسيرفر

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Background Removal Script
      run: python main.py

    - name: Upload Result Image
      uses: actions/upload-artifact@v4 # لرفع الصورة الناتجة كملف قابل للتحميل
      with:
        name: transparent-image
        path: output_transparent.png

